# See docs/settings-and-options.md for more information
base: &base
  service_provider_instance_filters:
    -
      name: "tag:use_case"
      values:
        - idp-web-tests
    -
      name: "tag-key"
      values:
        - test_ref
  aws_hosted_zone:
    name: sandbox.iam.s.uw.edu
    id: ZTMZX8EZCH1AH
    # This is not corroborated against any given endpoint;
    # this is the AWS default, and is used here for a polling task
    # Override this to extend the wait time for propagation if necessary;
    # will not change the actual host record.
    ttl: 300
  secret_manager:
    project: uwit-mci-iam
    secret_name: idp-web-test-config
    version: latest
  test_options: &base_test_options
    skip_test_service_provider_start: False
    skip_test_service_provider_stop: False
    use_local_secrets: false
    report_title: UW IdP Web Tests


docker_compose:
  <<: *base
  test_options: &compose_options
    <<: *base_test_options
    selenium_server: selenium:4444


# Run with --settings-profile in_development to
# run tests against eval quickly
# without shutting down service providers.
in_development:
  <<: *base
  test_options:
    <<: *compose_options
    skip_test_service_provider_start: True
    skip_test_service_provider_stop: True
    env: eval
