# This doesn't do anything yet. It's just scaffolding so that I can actually
# test the "real" manual workflow in the next iteration, since I can't test it
# until there is a `workflow_dispatch` trigger already in the mainline branch.

name: Run UW IdP Web Tests [Manual]

on:
  workflow_dispatch:
    inputs:
      target-idp-env:
        description: >
          target-idp-env. Acceptable values are `eval`, `prod`. The idp environment
          you want to test against.
        required: true
        default: eval

      target-idp-host:
        description: >
          target-idp-host. Optional. If provided, will add an /etc/hosts entry
          targeting this host.
        required: false

      slack-channel:
        description: >
          slack-channel. The channel to send a notification to, detailing the
          context and outcome of the test. (`/invite @iam-github-slack-crier`
          in the channel, if not already done.)
        required: true
        default: '#iam-bot-sandbox'

      pytest-args:
        description: >
          pytest-args. Any args you want to send to pytest. You do not ever need to
          supply `log_cli` arguments.
        required: false

      test-log-level:
        description: >
          test-log-level. If you need more information, you can set this to 'debug'.
        required: true
        default: info

jobs:
  scaffold:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.3.4
